### ISSUE TITLE
createThrottledMemo only updates once..

### ISSUE THREAD

**Issue by gukii** [solidjs-community/solid-primitives#196] opened 2022-08-27 05:34 UTC
I m trying out ```createThrottledMemo```. But can't get it to update more than once. Is it my mistake or a bug?
```
function ThrottleMemoTest() {

	const [count, setCount] = createSignal(1)
	const timer = setInterval( () => setCount(count() + 1), 1000 );
	
	const double_normal = () => count() * 2;						//works, updates
	const double_memo = createMemo( () => count() * 2, 0);			//works, updates
	const double_throttle = createThrottledMemo( prev => count() * 2, 2000);	//runs only once, why is it not updating?

	console.log('double_throttle:', double_throttle)
	onCleanup( () => clearInterval(timer) ); 
	
	return html`<div>count:${count}    double_throttle:${double_throttle}</div>`;
}
```

**Comment by thetarnav** [comment] 2022-08-30 15:51
Hey, thanks for the issue but I cannot reproduce—the primitive seems to work as expected.
Here is code from your snippet in a stackblitz sandbox:
https://stackblitz.com/edit/solid-vite-unocss-c4rf6p?file=index.tsx
And here is another example of the primitives:
https://stackblitz.com/edit/solid-vite-unocss-xmnubd?file=index.tsx
So I'll close this issue, but feel free to reopen it if you still have some issues. It would be helpful to see a reproduction though.

**Closed by thetarnav** 2022-08-30 15:51 UTC
