### ISSUE TITLE
Ensure primitives work with SSR

### ISSUE THREAD

**Issue by nksaraf** [solidjs-community/solid-primitives#147] opened 2022-06-10 14:05 UTC
For SSR with solid-js, specifically using with solid-start, we need to make sure we ship the correct format, i.e, we need to ship with the original JSX so that solid-start can compile differently for SSR and client-side bundles. 

Eg. @solid-primitives/props -> controlledProps has JSX.

I think using rollup-preset-solid has the correct configuration for this (though I am not sure).

This is a blocker for downstream libraries to support SSR properly.

**Comment by thetarnav** [comment] 2022-06-10 18:18
SSR support for `@solid-primitives/props` *should* be fixed now.
It's still not perfect for some reason, but this message might help: https://github.com/solidjs-community/solid-primitives/tree/main/packages/props#ssr-support
None of the rest uses JSX templates, so we are fine there.

**Comment by thetarnav** [comment] 2022-06-14 11:19
Okay, as I think the problem with `@solid-primitives/props` has been resolved and the rest of the primitives for fine in SSR env, I'm going to close this issue.
If anyone will have the misfortune of experiencing any sort of troubles with SSR caused by any of the solid-primitives packages, please let us know :)

**Closed by thetarnav** 2022-06-14 11:19 UTC
